Repository Gatsby-Lee/cloud-storage, pull requests merged in 2019-06, with the labels that each got.

#5 remove CR from gcs_storage.py
  cloud_storage/gcs_storage.py
Labels: formatting

#6 fix removed r char in gcs_storage.py
  cloud_storage/gcs_storage.py
Labels: bug

#9 Add playground and exception for asserting argument type, renamed ise…
  cloud_storage/excepts.py
  cloud_storage/gcs_storage.py
  playground/gcs_storage_playground.py
Labels: enhancement
